
print("Booleans")
print("True", True)
print("False", False)
print("True + True", True + True)
print("True + False", True + False)
print("False + False", False + False)
print("True and True", True and True)
print("True and False", True and False)
print("False and False", False and False)
print("True or True", True or True)
print("True or False", True or False)
print("False or False", False or False)
print("True xor True", True ^ True)
print("True xor False", True ^ False)
print("False xor False", False ^ False)
print("")
# print("\n")
print("Numbers")
print("2 + 3", 2+3)
print("5 -2 * 2", 5 - 2 * 2)
print("(5 -2) * 2", (5 - 2) * 2)
print("17 / 3", 17 / 3)
print("")
print("Strings")
test = 64567
print(test)
print("")
print("Quote \"me\" ")
HellowWorld = "Hello World!"
print(HellowWorld)
print(HellowWorld[0:5])
print(HellowWorld[1:5])
print(HellowWorld[6:])
print(HellowWorld[6:-1])
goodbye = "Goodbye"
print(goodbye + " Cruel " + HellowWorld[6:])

